version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: deploy/hooks/deregister_from_elb.sh
    - location: deploy/stop.sh
      runas: root
  AfterInstall:
    - location: deploy/pull.sh
      runas: root
  ApplicationStart:
    - location: deploy/start.sh
    - location: deploy/hooks/register_with_elb.sh
      runas: root
